### PR TITLE
csi game changes

### PR DESCRIPTION
**Pull request by ghost**
i had changed images in this game and made it look more good
csi_logo-removebg-preview
360_F_302319758_OFbmirBchJaszRPSHMO53NxtTnSOkvgy-modified

### CODE REVIEW

**Comment by arjun-sir** [comment]
Okay the circular images look amazing, just replace the wrong answer with the shinchan image so we dont have any conflicts with other pull requests

**Comment by ghost** [comment]
> Okay the circular images look amazing, just replace the wrong answer with the shinchan image so we dont have any conflicts with other pull requests

done changes now can u please accept

**Comment by arjun-sir** [comment]
You need make the shinchan image circular as well

**Comment by ghost** [comment]
Ok

**Pull request closed without merging**
