### PR TITLE
Fix: Fixed the bug highlighted in issue #46

### PR DESCRIPTION
**Pull request by NMN03**
Fixed the bug (#46 ) and also deleted unnecessary repetition of code.

### CODE REVIEW

**Comment by NMN03** [comment]
@SubstantialCattle5  @arjun-sir  could someone please look into this fix and merge if satisfied with the solution

**Comment by arjun-sir** [comment]
There is one small error, i.e. the options to choose from should go back to 2 when the wrong answer is selected.
Basically resetting the game

**Comment by NMN03** [comment]
Okay I'll try to reset the game .
Should I close this PR and make another one once I manage to get that issue right as well or you can still merge this one ?

**Comment by arjun-sir** [comment]
No its fine, ill let this PR be open till you are working on it. Tag me once you feel confident that you have solved the issue.
All the best !

**Comment by NMN03** [comment]
Thank you !
I'll get back to you as soon as I manage to work something out.

**Comment by NMN03** [comment]
Hey @arjun-sir 
I think I managed to reset the game but I fear the solution might be a bit crude.
Could you look into it and let me know if its fine and if needed help me figure out a more elegant solution?

**Comment by NMN03** [comment]
hey guys
Is this repo still active , because its been sometime since this pull request has been lying around😅

**Pull request merged**
