### PR TITLE
Web Dice

### PR DESCRIPTION
**Pull request by unknown7703**
This page re-direct user to randomly selected useless website on clicking redirect. (relative path must be maintained of existing pages ) t.aatreya(web dice enhancement extreme)

### CODE REVIEW

**Comment by arjun-sir** [comment]
http://127.0.0.1:5500/Forkthis/WebDice/Find-CSI/index.html

**Comment by arjun-sir** [comment]
.../Uselessredir/index.html# Redirectes me to:
.../Forkthis/WebDice/Find-CSI/index.html
While it should be "../Find-CSI/index.html"

**Comment by unknown7703** [comment]
Understood the errror, and i have made the changes

**Comment by arjun-sir** [comment]
Congrats on solving a hard issue!

**Pull request merged**
