### PR TITLE
Darkmode added (CSI)

### PR DESCRIPTION
**Pull request by SarveshN23**
#8 enhancement/darkmode(CSI)

### CODE REVIEW

**Comment by arjun-sir** [comment]
"Find CSI" text should be in Black colour in the light moe

**Comment by SarveshN23** [comment]
I have made an update to the code. Please check. Thankyou.

**Comment by arjun-sir** [comment]
Just remove the text shadow (in light mode) and we're good to go

**Comment by SarveshN23** [comment]
Done!

**Comment by arjun-sir** [comment]
Amazing :)

**Pull request merged**
