### PR TITLE
Increase image

### PR DESCRIPTION
**Pull request by unknown7703**
this increase images (4,8,16...)on each correct answer and reset on wrong ans.   -T.Aatreya

### CODE REVIEW

**Comment by arjun-sir** [comment]
Okay so I need images added vertically below so I can scroll down to choose, and also csi image position should be random and not fixed (i.e. csi logo can be placed on any of the 8 images)

**Comment by unknown7703** [comment]
Changes made , i didnt made randomize img fn as its another issue ,,and i was working on it ,,instead i am randomizing the divs.

**Comment by arjun-sir** [comment]
Okay so that issue was merged recently, please check it out and change your code accordingly

**Comment by unknown7703** [comment]
this branch has no conflict at the time of writing, please start reviewing from the oldest pr ,how will i be able to account for changes in master(from new merges)that came  after my pr ,and people are changing class name and image name breaking code for others please ask them no to do so .

**Comment by arjun-sir** [comment]
Yes good job, it works now

**Comment by arjun-sir** [comment]
Congrats on solving an extreme issue!

**Pull request merged**
