### PR TITLE
#13 Find a streak

### PR DESCRIPTION
**Pull request by aryan16x**
#13 Added text box which shows you the streak that how many times you guess correct CSI and reset after every wrong guess

### CODE REVIEW

**Comment by arjun-sir** [comment]
Hi, actually we need the users highest streak to display. 
Also mention "your highest streak:" on the UI

**Comment by aryan16x** [comment]
But that one is issue #14 ig

**Comment by arjun-sir** [comment]
No actually #14 is about highest streak between all of the users combined and this is for 1 particular user only

**Comment by aryan16x** [comment]
Yaa, now I added that highest streak part. You can review it.

**Comment by arjun-sir** [comment]
Yes, this is perfect :)

**Pull request merged**
